"""add waitlist table

Revision ID: 572539d3e7b4
Revises: f2493329a299
Create Date: 2026-04-01 11:00:48.392144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572539d3e7b4'
down_revision: Union[str, Sequence[str], None] = 'f2493329a299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('room_block_id', sa.UUID(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('offer_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_block_id'], ['room_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_event_id'), 'waitlist', ['event_id'], unique=False)
    op.create_index(op.f('ix_waitlist_guest_id'), 'waitlist', ['guest_id'], unique=False)
    op.create_index(op.f('ix_waitlist_room_block_id'), 'waitlist', ['room_block_id'], unique=False)
    op.create_index(op.f('ix_waitlist_room_type'), 'waitlist', ['room_type'], unique=False)
    op.create_index(op.f('ix_waitlist_status'), 'waitlist', ['status'], unique=False)
    op.create_index(op.f('ix_waitlist_tenant_id'), 'waitlist', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_tenant_id'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_status'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_room_type'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_room_block_id'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_guest_id'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_event_id'), table_name='waitlist')
    op.drop_table('waitlist')
    # ### end Alembic commands ###
