"""add channel to notification_logs

Revision ID: a24b6fe0e8b6
Revises: 661a5e92feda
Create Date: 2026-04-05 15:21:26.509310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24b6fe0e8b6'
down_revision: Union[str, Sequence[str], None] = '661a5e92feda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_logs', sa.Column('channel', sa.String(length=20), server_default='email', nullable=False))
    op.create_index(op.f('ix_notification_logs_channel'), 'notification_logs', ['channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_channel'), table_name='notification_logs')
    op.drop_column('notification_logs', 'channel')
    # ### end Alembic commands ###
