"""add microsite tables

Revision ID: d23d3a109c33
Revises: 6c806369a2fc
Create Date: 2026-04-01 23:09:37.997979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23d3a109c33'
down_revision: Union[str, Sequence[str], None] = '6c806369a2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microsites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('theme_color', sa.String(length=50), nullable=True),
    sa.Column('hero_image_url', sa.String(length=1024), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_microsites_slug'), 'microsites', ['slug'], unique=True)
    op.create_index(op.f('ix_microsites_tenant_id'), 'microsites', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microsites_tenant_id'), table_name='microsites')
    op.drop_index(op.f('ix_microsites_slug'), table_name='microsites')
    op.drop_table('microsites')
    # ### end Alembic commands ###
