"""add room blocks tables

Revision ID: f2493329a299
Revises: 9fc702740ad7
Create Date: 2026-04-01 10:48:20.801975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2493329a299'
down_revision: Union[str, Sequence[str], None] = '9fc702740ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_blocks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('hold_deadline', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_blocks_event_id'), 'room_blocks', ['event_id'], unique=False)
    op.create_index(op.f('ix_room_blocks_tenant_id'), 'room_blocks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_room_blocks_venue_id'), 'room_blocks', ['venue_id'], unique=False)
    op.create_table('room_block_allotments',
    sa.Column('room_block_id', sa.UUID(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('booked_rooms', sa.Integer(), nullable=False),
    sa.Column('held_rooms', sa.Integer(), nullable=False),
    sa.Column('negotiated_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_block_id'], ['room_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_block_id', 'room_type', name='uq_allotment_block_type')
    )
    op.create_index(op.f('ix_room_block_allotments_room_block_id'), 'room_block_allotments', ['room_block_id'], unique=False)
    op.create_index(op.f('ix_room_block_allotments_room_type'), 'room_block_allotments', ['room_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_block_allotments_room_type'), table_name='room_block_allotments')
    op.drop_index(op.f('ix_room_block_allotments_room_block_id'), table_name='room_block_allotments')
    op.drop_table('room_block_allotments')
    op.drop_index(op.f('ix_room_blocks_venue_id'), table_name='room_blocks')
    op.drop_index(op.f('ix_room_blocks_tenant_id'), table_name='room_blocks')
    op.drop_index(op.f('ix_room_blocks_event_id'), table_name='room_blocks')
    op.drop_table('room_blocks')
    # ### end Alembic commands ###
