"""
Guest Service — all business logic for guest management.

Separated from the API layer so that:
1. Routes only handle HTTP (request/response, status codes)
2. This service handles DB operations, validation, and business rules
3. Background tasks (Celery) can call these functions directly

Key rules enforced here (not in the route):
  - A guest email must be unique within an event
  - Bulk import: if one row fails, skip it and report — don't abort the batch
  - Deactivating a guest (soft-delete) never deletes historical booking records
  - booking_token is generated by the model default — never set manually
"""

import uuid
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.guest import Guest
from app.schemas.guest import (
    GuestBulkCreate,
    GuestBulkCreateResponse,
    GuestCreate,
    GuestResponse,
    GuestUpdate,
)


async def _verify_event_ownership(
    event_id: uuid.UUID,
    tenant_id: uuid.UUID,
    db: AsyncSession,
) -> None:
    """
    Confirm the event belongs to this tenant before touching its guests.
    Raises ValueError if the event doesn't exist or belongs to another tenant.

    Imported lazily to avoid circular imports between models.
    """
    from app.models.event import Event

    result = await db.execute(
        select(Event).where(Event.id == event_id, Event.tenant_id == tenant_id)
    )
    if result.scalar_one_or_none() is None:
        raise ValueError(f"Event {event_id} not found or not accessible.")


# ---------------------------------------------------------------------------
# Create
# ---------------------------------------------------------------------------


async def create_guest(
    data: GuestCreate,
    tenant_id: uuid.UUID,
    event_id: uuid.UUID,
    db: AsyncSession,
) -> Guest:
    """
    Create a single guest for an event.

    Raises:
      ValueError  — if the event doesn't belong to this tenant
      ValueError  — if the email already exists for this event
    """
    await _verify_event_ownership(event_id, tenant_id, db)

    guest = Guest(
        tenant_id=tenant_id,
        event_id=event_id,
        name=data.name,
        email=data.email,
        phone=data.phone,
        category=data.category,
        dietary_requirements=data.dietary_requirements or {},
        extra_data=data.extra_data or {},
    )
    db.add(guest)
    try:
        await db.commit()
        await db.refresh(guest)
    except IntegrityError:
        await db.rollback()
        raise ValueError(
            f"A guest with email '{data.email}' is already registered for this event."
        )
    return guest


# ---------------------------------------------------------------------------
# Bulk Create
# ---------------------------------------------------------------------------


async def bulk_create_guests(
    data: GuestBulkCreate,
    tenant_id: uuid.UUID,
    event_id: uuid.UUID,
    db: AsyncSession,
) -> GuestBulkCreateResponse:
    """
    Import multiple guests in one request.

    Strategy: try each guest individually so that one bad row
    (duplicate email, validation failure) doesn't abort the entire batch.
    Returns a summary: how many were created, how many skipped, and why.

    This is intentionally NOT a single bulk INSERT so we get per-row
    error reporting. For 500 rows the overhead is acceptable.
    """
    await _verify_event_ownership(event_id, tenant_id, db)

    created_guests: list[Guest] = []
    skipped = 0
    errors: list[str] = []

    # Pre-load existing emails for this event to avoid N round-trips
    existing_emails_result = await db.execute(
        select(Guest.email).where(
            Guest.event_id == event_id,
            Guest.is_active == True,  # noqa: E712
            Guest.email.isnot(None),
        )
    )
    existing_emails: set[str | None] = {
        row[0].lower() for row in existing_emails_result.all() if row[0]
    }

    for item in data.guests:
        # Check for duplicate within this batch or existing records
        email_lower = item.email.lower() if item.email else None
        if email_lower and email_lower in existing_emails:
            skipped += 1
            errors.append(
                f"Skipped '{item.name}': email '{item.email}' already registered."
            )
            continue

        guest = Guest(
            tenant_id=tenant_id,
            event_id=event_id,
            name=item.name,
            email=item.email,
            phone=item.phone,
            category=item.category,
            dietary_requirements=item.dietary_requirements or {},
            extra_data=item.extra_data or {},
        )
        db.add(guest)

        try:
            await db.flush()  # Write to DB within transaction, get the ID
            created_guests.append(guest)
            if email_lower:
                existing_emails.add(email_lower)  # Track in-batch to catch dupes
        except IntegrityError:
            await db.rollback()
            skipped += 1
            errors.append(
                f"Skipped '{item.name}': database constraint violation."
            )
            continue

    await db.commit()

    # Refresh all created guests to get DB-generated fields
    for guest in created_guests:
        await db.refresh(guest)

    return GuestBulkCreateResponse(
        created=len(created_guests),
        skipped=skipped,
        errors=errors,
        guests=[GuestResponse.model_validate(g) for g in created_guests],
    )


# ---------------------------------------------------------------------------
# Read
# ---------------------------------------------------------------------------


async def get_guests(
    event_id: uuid.UUID,
    tenant_id: uuid.UUID,
    db: AsyncSession,
    page: int = 1,
    page_size: int = 20,
    category_filter: str | None = None,
    active_only: bool = True,
) -> tuple[list[Guest], int]:
    """
    Get paginated guests for an event.
    Returns (guests, total_count).
    """
    query = select(Guest).where(
        Guest.event_id == event_id,
        Guest.tenant_id == tenant_id,
    )

    if active_only:
        query = query.where(Guest.is_active == True)  # noqa: E712

    if category_filter:
        query = query.where(Guest.category == category_filter.lower())

    # Total count
    count_query = select(func.count()).select_from(query.subquery())
    total = (await db.execute(count_query)).scalar() or 0

    # Paginated results — ordered by name for consistent output
    query = query.order_by(Guest.name.asc())
    query = query.offset((page - 1) * page_size).limit(page_size)
    result = await db.execute(query)
    guests = list(result.scalars().all())

    return guests, total


async def get_guest_by_id(
    guest_id: uuid.UUID,
    event_id: uuid.UUID,
    tenant_id: uuid.UUID,
    db: AsyncSession,
) -> Guest | None:
    """Get a single guest by ID, scoped to the event and tenant."""
    result = await db.execute(
        select(Guest).where(
            Guest.id == guest_id,
            Guest.event_id == event_id,
            Guest.tenant_id == tenant_id,
        )
    )
    return result.scalar_one_or_none()


async def get_guest_by_token(
    booking_token: uuid.UUID,
    db: AsyncSession,
) -> Guest | None:
    """
    Look up a guest by their magic-link token.

    This is a PUBLIC lookup — no tenant scoping because the token
    itself is the secret. Used by microsite and booking endpoints.
    Only returns active guests.
    """
    result = await db.execute(
        select(Guest).where(
            Guest.booking_token == booking_token,
            Guest.is_active == True,  # noqa: E712
        )
    )
    return result.scalar_one_or_none()


# ---------------------------------------------------------------------------
# Update
# ---------------------------------------------------------------------------


async def update_guest(
    guest_id: uuid.UUID,
    data: GuestUpdate,
    event_id: uuid.UUID,
    tenant_id: uuid.UUID,
    db: AsyncSession,
) -> Guest | None:
    """
    Partial update of a guest. Only updates fields that were explicitly set.
    Returns None if the guest doesn't exist or doesn't belong to this tenant/event.
    """
    guest = await get_guest_by_id(guest_id, event_id, tenant_id, db)
    if guest is None:
        return None

    update_data = data.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr(guest, field, value)

    try:
        await db.commit()
        await db.refresh(guest)
    except IntegrityError:
        await db.rollback()
        raise ValueError(
            f"Email '{data.email}' is already registered for this event."
        )

    return guest


# ---------------------------------------------------------------------------
# Deactivate (soft-delete)
# ---------------------------------------------------------------------------


async def deactivate_guest(
    guest_id: uuid.UUID,
    event_id: uuid.UUID,
    tenant_id: uuid.UUID,
    db: AsyncSession,
) -> Guest | None:
    """
    Soft-delete a guest by setting is_active = False.

    We never hard-delete guests because:
    1. They may have booking history that must be preserved
    2. Accidental deletes should be reversible by setting is_active=True

    Returns the deactivated guest, or None if not found.
    """
    guest = await get_guest_by_id(guest_id, event_id, tenant_id, db)
    if guest is None:
        return None

    guest.is_active = False
    await db.commit()
    await db.refresh(guest)
    return guest
